title: Colonial Heritage IVR Project
baseurl: "/IVR-colonial-heritage/index" # the subpath of your site, e.g. /blog
url: "https://n-maronic.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-minimal
